"""
Integration Tests for Student Handout Generator

Tests complete end-to-end workflows:
- Full pipeline: Parse → Transform → Load Questions → Process Images → Layout → PDF
- AI question generation → Staging → Review → Approval → Handout generation
- Batch processing workflows
- Error handling across components
- Performance validation

These tests verify that all components work together correctly.
"""

import pytest
import json
import time
from pathlib import Path
from datetime import datetime
from unittest.mock import Mock, patch, MagicMock

from src.framework_parser import FrameworkParser
from src.content_transformer import ContentTransformer
from src.question_loader import QuestionLoader
from src.question_generator import QuestionGenerator
from src.question_reviewer import QuestionReviewer
from src.image_processor import ImageProcessor
from src.layout_engine import LayoutEngine
from src.pdf_renderer import PDFRenderer
from src.models import QuestionStatus, QuestionSource
from src.error_handler import HandoutGeneratorError


class TestCompletePipeline:
    """Test the complete end-to-end pipeline"""

    def test_complete_pipeline_single_module(
        self,
        test_config,
        sample_framework_content,
        sample_questions,
        temp_output_dir,
        temp_question_bank_dir,
        create_question_file,
        create_framework_file
    ):
        """
        Test: Parse → Transform → Load Questions → Process Images → Layout → PDF

        This is the core integration test verifying the entire pipeline works.
        """
        # 1. Create test framework file
        framework_path = temp_output_dir / "test_framework.md"
        create_framework_file(framework_path, sample_framework_content)

        # 2. Create approved questions file
        questions_path = temp_question_bank_dir["approved"] / "test-module-0.json"
        create_question_file(questions_path, sample_questions, "test-module-0")

        # Update config to use temp directories
        test_config.config["questions"]["approved_directory"] = str(temp_question_bank_dir["approved"])
        test_config.config["global"]["output_directory"] = str(temp_output_dir)

        # STEP 1: Parse framework
        parser = FrameworkParser()
        parse_result = parser.parse_file(framework_path)

        assert parse_result.success, f"Parsing failed: {parse_result.errors}"
        assert parse_result.metadata is not None
        assert parse_result.metadata.module_number == 0
        assert len(parse_result.sections) > 0

        # STEP 2: Transform content
        transformer = ContentTransformer(test_config)
        transformed_sections = transformer.transform(parse_result.sections)

        # Verify transformation
        assert len(transformed_sections) > 0
        # Verify instructor-only content removed (if any existed)
        for section in transformed_sections:
            assert "For Instructors" not in section.content

        # STEP 3: Load approved questions
        loader = QuestionLoader(test_config)
        questions = loader.load_questions("test-module-0")

        assert len(questions) > 0
        assert all(q.status == QuestionStatus.APPROVED for q in questions)

        # STEP 4: Process images (using mock for this test)
        processor = ImageProcessor(test_config)
        # For integration test, we'll process with placeholders for missing images
        image_refs = parse_result.images
        processed_images = processor.process_images(image_refs)

        # Images should either exist or have placeholders
        assert len(processed_images) >= 0

        # STEP 5: Create layout (HTML)
        layout_engine = LayoutEngine(test_config)

        # Combine all content
        from src.models import HandoutDocument, TOCEntry

        handout_doc = HandoutDocument(
            metadata=parse_result.metadata,
            sections=transformed_sections,
            questions=questions,
            images=processed_images,
            toc=[],  # TOC generated by layout engine
            generation_timestamp=datetime.now(),
            config_used=test_config.to_dict(),
            output_path=temp_output_dir / "test_handout.pdf",
            warnings=[],
            question_review_complete=True
        )

        html_output = layout_engine.render(handout_doc)

        # Verify HTML output
        assert "<html>" in html_output
        assert "dark" in html_output.lower()  # Dark theme
        assert parse_result.metadata.module_title in html_output

        # STEP 6: Render PDF
        renderer = PDFRenderer(test_config)
        pdf_path = renderer.render_handout(
            html_content=html_output,
            output_path=temp_output_dir / "test_handout.pdf",
            metadata=parse_result.metadata
        )

        # Verify PDF was created
        assert pdf_path.exists()
        assert pdf_path.stat().st_size > 0

        # Verify PDF header (basic validation)
        with open(pdf_path, 'rb') as f:
            header = f.read(4)
            assert header == b'%PDF', "File is not a valid PDF"

        print(f"✓ Complete pipeline test passed. PDF size: {pdf_path.stat().st_size} bytes")

    def test_pipeline_with_missing_components(
        self,
        test_config,
        sample_framework_content,
        temp_output_dir,
        create_framework_file
    ):
        """
        Test pipeline handles missing questions gracefully
        """
        # Create framework without questions
        framework_path = temp_output_dir / "test_framework.md"
        create_framework_file(framework_path, sample_framework_content)

        # Disable questions in config
        test_config.config["questions"]["enabled"] = False

        # Parse and transform
        parser = FrameworkParser()
        parse_result = parser.parse_file(framework_path)
        assert parse_result.success

        transformer = ContentTransformer(test_config)
        transformed_sections = transformer.transform(parse_result.sections)

        # Should work without questions
        layout_engine = LayoutEngine(test_config)

        from src.models import HandoutDocument
        handout_doc = HandoutDocument(
            metadata=parse_result.metadata,
            sections=transformed_sections,
            questions=[],  # No questions
            images=[],
            toc=[],
            generation_timestamp=datetime.now(),
            config_used=test_config.to_dict(),
            output_path=temp_output_dir / "no_questions.pdf",
            warnings=["Questions disabled"],
            question_review_complete=True
        )

        html_output = layout_engine.render(handout_doc)
        assert "<html>" in html_output

        print("✓ Pipeline works without questions")

    def test_pipeline_performance_timing(
        self,
        test_config,
        sample_framework_content,
        sample_questions,
        temp_output_dir,
        temp_question_bank_dir,
        create_question_file,
        create_framework_file
    ):
        """
        Test pipeline performance meets requirements (< 5 minutes for small module)
        """
        framework_path = temp_output_dir / "test_framework.md"
        create_framework_file(framework_path, sample_framework_content)

        questions_path = temp_question_bank_dir["approved"] / "test-module-0.json"
        create_question_file(questions_path, sample_questions, "test-module-0")

        test_config.config["questions"]["approved_directory"] = str(temp_question_bank_dir["approved"])
        test_config.config["global"]["output_directory"] = str(temp_output_dir)

        start_time = time.time()

        # Run full pipeline
        parser = FrameworkParser()
        parse_result = parser.parse_file(framework_path)

        transformer = ContentTransformer(test_config)
        transformed_sections = transformer.transform(parse_result.sections)

        loader = QuestionLoader(test_config)
        questions = loader.load_questions("test-module-0")

        processor = ImageProcessor(test_config)
        processed_images = processor.process_images(parse_result.images)

        layout_engine = LayoutEngine(test_config)

        from src.models import HandoutDocument
        handout_doc = HandoutDocument(
            metadata=parse_result.metadata,
            sections=transformed_sections,
            questions=questions,
            images=processed_images,
            toc=[],
            generation_timestamp=datetime.now(),
            config_used=test_config.to_dict(),
            output_path=temp_output_dir / "perf_test.pdf",
            warnings=[],
            question_review_complete=True
        )

        html_output = layout_engine.render(handout_doc)

        renderer = PDFRenderer(test_config)
        pdf_path = renderer.render_handout(
            html_content=html_output,
            output_path=temp_output_dir / "perf_test.pdf",
            metadata=parse_result.metadata
        )

        elapsed_time = time.time() - start_time

        # For small framework (<500 lines), should be < 30 seconds
        # (PRD specifies < 2 min for small, < 5 min for large)
        assert elapsed_time < 30, f"Pipeline too slow: {elapsed_time:.2f}s"

        print(f"✓ Pipeline performance: {elapsed_time:.2f}s (target: <30s for small module)")


class TestAIQuestionWorkflow:
    """Test AI question generation, staging, review, and approval workflow"""

    @patch('anthropic.Anthropic')
    def test_ai_question_generation_to_approval(
        self,
        mock_anthropic_class,
        test_config,
        sample_framework_content,
        temp_question_bank_dir,
        temp_output_dir,
        create_framework_file
    ):
        """
        Test: Generate AI questions → Save staging → Load for review → Approve → Load for handout
        """
        # Setup mock Anthropic client
        mock_client = MagicMock()
        mock_response = MagicMock()
        mock_response.content = [
            MagicMock(text=json.dumps({
                "questions": [
                    {
                        "id": "ai-q1",
                        "type": "multiple_choice",
                        "question_text": "What is machine learning?",
                        "options": ["A database", "A programming language", "Getting computers to learn", "Cloud computing"],
                        "correct_answer": "C",
                        "explanation": "ML is about getting computers to learn.",
                        "difficulty": "easy",
                        "points": 1,
                        "learning_outcome": "Understand ML basics",
                        "source_section": "session-1"
                    }
                ]
            }))
        ]
        mock_client.messages.create.return_value = mock_response
        mock_anthropic_class.return_value = mock_client

        # Update config
        test_config.config["questions"]["staging_directory"] = str(temp_question_bank_dir["staging"])
        test_config.config["questions"]["approved_directory"] = str(temp_question_bank_dir["approved"])

        # Create framework
        framework_path = temp_output_dir / "test_framework.md"
        create_framework_file(framework_path, sample_framework_content)

        # Parse framework to get sections
        parser = FrameworkParser()
        parse_result = parser.parse_file(framework_path)
        assert parse_result.success

        # STEP 1: Generate AI questions
        generator = QuestionGenerator(test_config)

        # Generate questions for first section
        section = parse_result.sections[0]
        questions = generator.generate_for_section(section, module_id="test-module-0")

        assert len(questions) > 0
        assert all(q.status == QuestionStatus.PENDING_REVIEW for q in questions)
        assert all(q.source == QuestionSource.AI_GENERATED for q in questions)

        # STEP 2: Save to staging
        staging_file = temp_question_bank_dir["staging"] / "test-module-0-staging.json"
        generator.save_staging_file("test-module-0", questions, staging_file)

        assert staging_file.exists()

        # Verify staging file format
        with open(staging_file) as f:
            staging_data = json.load(f)
            assert staging_data["module_id"] == "test-module-0"
            assert "questions_pending" in staging_data
            assert len(staging_data["questions"]) > 0

        # STEP 3: Simulate review (approve all questions)
        reviewer = QuestionReviewer(test_config)

        # Load staging questions
        with open(staging_file) as f:
            staging_data = json.load(f)

        from src.models import Question
        staging_questions = [Question.from_dict(q) for q in staging_data["questions"]]

        # Approve all questions (simulated)
        approved_questions = []
        for q in staging_questions:
            q.status = QuestionStatus.APPROVED
            q.reviewed_at = datetime.now()
            approved_questions.append(q)

        # Save approved questions
        approved_file = temp_question_bank_dir["approved"] / "test-module-0.json"
        approved_data = {
            "module_id": "test-module-0",
            "module_title": parse_result.metadata.module_title,
            "version": "1.0",
            "last_reviewed": datetime.now().isoformat(),
            "questions": [q.to_dict() for q in approved_questions]
        }

        with open(approved_file, 'w') as f:
            json.dump(approved_data, f, indent=2)

        # STEP 4: Load approved questions for handout generation
        loader = QuestionLoader(test_config)
        loaded_questions = loader.load_questions("test-module-0")

        assert len(loaded_questions) > 0
        assert all(q.status == QuestionStatus.APPROVED for q in loaded_questions)
        assert loaded_questions[0].question_text == "What is machine learning?"

        print("✓ AI question workflow: Generate → Stage → Review → Approve → Load")

    @patch('anthropic.Anthropic')
    def test_ai_generation_with_retry_on_failure(
        self,
        mock_anthropic_class,
        test_config,
        sample_framework_content,
        temp_question_bank_dir,
        temp_output_dir,
        create_framework_file
    ):
        """
        Test AI generation retries on failure and eventually succeeds
        """
        mock_client = MagicMock()

        # First two calls fail, third succeeds
        call_count = [0]

        def side_effect(*args, **kwargs):
            call_count[0] += 1
            if call_count[0] < 3:
                raise Exception("API Error: Rate limit")
            else:
                # Success on third try
                mock_response = MagicMock()
                mock_response.content = [
                    MagicMock(text=json.dumps({
                        "questions": [
                            {
                                "id": "retry-q1",
                                "type": "true_false",
                                "question_text": "Retry worked?",
                                "options": ["True", "False"],
                                "correct_answer": "True",
                                "explanation": "Yes, retry succeeded!",
                                "difficulty": "easy",
                                "points": 1,
                                "learning_outcome": "Test retries",
                                "source_section": "intro"
                            }
                        ]
                    }))
                ]
                return mock_response

        mock_client.messages.create.side_effect = side_effect
        mock_anthropic_class.return_value = mock_client

        test_config.config["questions"]["staging_directory"] = str(temp_question_bank_dir["staging"])

        # Create framework
        framework_path = temp_output_dir / "test_framework.md"
        create_framework_file(framework_path, sample_framework_content)

        parser = FrameworkParser()
        parse_result = parser.parse_file(framework_path)

        # Generate with retries
        generator = QuestionGenerator(test_config)
        section = parse_result.sections[0]

        # Should succeed after retries
        questions = generator.generate_for_section(section, module_id="test-retry")

        assert len(questions) > 0
        assert call_count[0] == 3, "Should have retried 3 times"

        print("✓ AI generation retry logic works")

    def test_blocking_on_unreviewed_questions(
        self,
        test_config,
        temp_question_bank_dir,
        pending_questions,
        create_question_file
    ):
        """
        Test that handout generation is blocked if questions are unreviewed
        """
        # Create staging file with pending questions
        staging_path = temp_question_bank_dir["staging"] / "test-module-0-staging.json"
        create_question_file(staging_path, pending_questions, "test-module-0")

        test_config.config["questions"]["staging_directory"] = str(temp_question_bank_dir["staging"])
        test_config.config["questions"]["approved_directory"] = str(temp_question_bank_dir["approved"])

        # Try to load questions - should find none approved
        loader = QuestionLoader(test_config)

        # Check review status
        status = loader.get_review_status("test-module-0")

        assert status["pending_count"] > 0
        assert status["approved_count"] == 0
        assert not status["review_complete"]

        print("✓ Correctly blocks on unreviewed questions")


class TestBatchProcessing:
    """Test batch processing workflows"""

    def test_batch_processing_multiple_modules(
        self,
        test_config,
        sample_framework_content,
        sample_questions,
        temp_output_dir,
        temp_question_bank_dir,
        create_question_file,
        create_framework_file
    ):
        """
        Test: Discover frameworks → Check review status → Batch process → Verify outputs
        """
        # Create multiple framework files
        modules = ["module-0", "module-1", "module-2"]

        for module_id in modules:
            # Create framework file
            framework_path = temp_output_dir / "frameworks" / f"{module_id}-framework.md"
            framework_path.parent.mkdir(parents=True, exist_ok=True)
            create_framework_file(framework_path, sample_framework_content)

            # Create approved questions
            questions_path = temp_question_bank_dir["approved"] / f"{module_id}.json"
            create_question_file(questions_path, sample_questions, module_id)

        test_config.config["questions"]["approved_directory"] = str(temp_question_bank_dir["approved"])
        test_config.config["global"]["output_directory"] = str(temp_output_dir)

        # Simulate batch processor
        results = {}

        for module_id in modules:
            framework_path = temp_output_dir / "frameworks" / f"{module_id}-framework.md"

            try:
                # Parse
                parser = FrameworkParser()
                parse_result = parser.parse_file(framework_path)

                if not parse_result.success:
                    results[module_id] = {"success": False, "error": "Parse failed"}
                    continue

                # Transform
                transformer = ContentTransformer(test_config)
                sections = transformer.transform(parse_result.sections)

                # Load questions
                loader = QuestionLoader(test_config)
                questions = loader.load_questions(module_id)

                # Check review status
                status = loader.get_review_status(module_id)
                if not status["review_complete"]:
                    results[module_id] = {"success": False, "blocked": True, "reason": "Unreviewed questions"}
                    continue

                # Process images
                processor = ImageProcessor(test_config)
                images = processor.process_images(parse_result.images)

                # Layout
                layout_engine = LayoutEngine(test_config)

                from src.models import HandoutDocument
                handout_doc = HandoutDocument(
                    metadata=parse_result.metadata,
                    sections=sections,
                    questions=questions,
                    images=images,
                    toc=[],
                    generation_timestamp=datetime.now(),
                    config_used=test_config.to_dict(),
                    output_path=temp_output_dir / f"{module_id}-handout.pdf",
                    warnings=[],
                    question_review_complete=True
                )

                html = layout_engine.render(handout_doc)

                # PDF
                renderer = PDFRenderer(test_config)
                pdf_path = renderer.render_handout(
                    html_content=html,
                    output_path=temp_output_dir / f"{module_id}-handout.pdf",
                    metadata=parse_result.metadata
                )

                results[module_id] = {"success": True, "pdf_path": str(pdf_path)}

            except Exception as e:
                results[module_id] = {"success": False, "error": str(e)}

        # Verify all succeeded
        assert len(results) == 3
        assert all(results[m]["success"] for m in modules)

        for module_id in modules:
            pdf_path = Path(results[module_id]["pdf_path"])
            assert pdf_path.exists()
            assert pdf_path.stat().st_size > 0

        print(f"✓ Batch processed {len(modules)} modules successfully")

    def test_batch_with_mixed_review_states(
        self,
        test_config,
        sample_framework_content,
        sample_questions,
        pending_questions,
        temp_output_dir,
        temp_question_bank_dir,
        create_question_file,
        create_framework_file
    ):
        """
        Test batch processing with some modules approved, some pending
        """
        # Module 0: Approved
        framework_0 = temp_output_dir / "frameworks" / "module-0-framework.md"
        framework_0.parent.mkdir(parents=True, exist_ok=True)
        create_framework_file(framework_0, sample_framework_content)

        questions_0 = temp_question_bank_dir["approved"] / "module-0.json"
        create_question_file(questions_0, sample_questions, "module-0")

        # Module 1: Pending review
        framework_1 = temp_output_dir / "frameworks" / "module-1-framework.md"
        create_framework_file(framework_1, sample_framework_content)

        staging_1 = temp_question_bank_dir["staging"] / "module-1-staging.json"
        create_question_file(staging_1, pending_questions, "module-1")

        test_config.config["questions"]["staging_directory"] = str(temp_question_bank_dir["staging"])
        test_config.config["questions"]["approved_directory"] = str(temp_question_bank_dir["approved"])

        # Check review status for both
        loader = QuestionLoader(test_config)

        status_0 = loader.get_review_status("module-0")
        status_1 = loader.get_review_status("module-1")

        assert status_0["review_complete"] is True
        assert status_1["review_complete"] is False

        # Module 0 should process, module 1 should be blocked
        print("✓ Batch correctly identifies mixed review states")


class TestErrorHandling:
    """Test error handling across the pipeline"""

    def test_missing_framework_file(self, test_config):
        """Test handling of missing framework file"""
        parser = FrameworkParser()
        result = parser.parse_file(Path("/nonexistent/file.md"))

        assert not result.success
        assert len(result.errors) > 0
        assert "not found" in result.errors[0].lower() or "does not exist" in result.errors[0].lower()

    def test_malformed_markdown(
        self,
        test_config,
        fixtures_dir
    ):
        """Test handling of malformed markdown"""
        malformed_file = fixtures_dir / "sample_framework_malformed.md"

        parser = FrameworkParser()
        result = parser.parse_file(malformed_file)

        # Should fail gracefully
        assert not result.success
        assert len(result.errors) > 0

    def test_missing_images_graceful_handling(
        self,
        test_config,
        temp_output_dir
    ):
        """Test that missing images are handled with placeholders"""
        processor = ImageProcessor(test_config)

        from src.models import ImageReference
        missing_image = ImageReference(
            id="missing-1",
            original_path="/nonexistent/image.png",
            alt_text="Missing Image"
        )

        processed = processor.process_images([missing_image])

        # Should process with placeholder
        assert len(processed) == 1
        assert processed[0].placeholder_used is True
        assert not processed[0].exists

    def test_api_failure_fallback(
        self,
        test_config,
        sample_framework_content,
        temp_question_bank_dir,
        temp_output_dir,
        create_framework_file
    ):
        """Test graceful handling of API failures"""
        with patch('anthropic.Anthropic') as mock_anthropic_class:
            mock_client = MagicMock()
            mock_client.messages.create.side_effect = Exception("API Error")
            mock_anthropic_class.return_value = mock_client

            test_config.config["questions"]["staging_directory"] = str(temp_question_bank_dir["staging"])
            test_config.config["questions"]["ai_generation"]["max_retries"] = 1  # Fail fast

            framework_path = temp_output_dir / "test_framework.md"
            create_framework_file(framework_path, sample_framework_content)

            parser = FrameworkParser()
            parse_result = parser.parse_file(framework_path)

            generator = QuestionGenerator(test_config)
            section = parse_result.sections[0]

            # Should handle API failure gracefully
            with pytest.raises(Exception) as exc_info:
                generator.generate_for_section(section, module_id="test-fail")

            assert "API Error" in str(exc_info.value)

        print("✓ API failures handled gracefully")


class TestPerformanceRequirements:
    """Test performance requirements from PRD"""

    def test_small_framework_processing_time(
        self,
        test_config,
        sample_framework_content,
        sample_questions,
        temp_output_dir,
        temp_question_bank_dir,
        create_question_file,
        create_framework_file
    ):
        """
        Test that small frameworks (<500 lines) process in < 2 minutes
        PRD Section 15.5: Processing time targets
        """
        framework_path = temp_output_dir / "small_framework.md"
        create_framework_file(framework_path, sample_framework_content)

        questions_path = temp_question_bank_dir["approved"] / "small-module.json"
        create_question_file(questions_path, sample_questions, "small-module")

        test_config.config["questions"]["approved_directory"] = str(temp_question_bank_dir["approved"])
        test_config.config["global"]["output_directory"] = str(temp_output_dir)

        start_time = time.time()

        # Full pipeline
        parser = FrameworkParser()
        parse_result = parser.parse_file(framework_path)
        assert parse_result.success

        transformer = ContentTransformer(test_config)
        sections = transformer.transform(parse_result.sections)

        loader = QuestionLoader(test_config)
        questions = loader.load_questions("small-module")

        processor = ImageProcessor(test_config)
        images = processor.process_images(parse_result.images)

        layout_engine = LayoutEngine(test_config)

        from src.models import HandoutDocument
        handout_doc = HandoutDocument(
            metadata=parse_result.metadata,
            sections=sections,
            questions=questions,
            images=images,
            toc=[],
            generation_timestamp=datetime.now(),
            config_used=test_config.to_dict(),
            output_path=temp_output_dir / "small.pdf",
            warnings=[],
            question_review_complete=True
        )

        html = layout_engine.render(handout_doc)

        renderer = PDFRenderer(test_config)
        pdf_path = renderer.render_handout(
            html_content=html,
            output_path=temp_output_dir / "small.pdf",
            metadata=parse_result.metadata
        )

        elapsed = time.time() - start_time

        # Should be well under 2 minutes (120 seconds)
        # For small files, target is actually < 30 seconds
        assert elapsed < 120, f"Too slow: {elapsed:.2f}s (target: <120s)"

        print(f"✓ Small framework processed in {elapsed:.2f}s (target: <120s)")
